language: node_js
node_js:
  - '10'
  - '8'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm test
after_success:
  - echo "All good! 🎉"